#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo rm /var/www/html/index.nginx-debian.html
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart