#!/usr/bin/env bash
# Setup Nginx redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo rm /var/www/html/index.nginx-debian.html
sudo echo 'Hello World' >> /var/www/html/index.nginx-debian.html
sudo sed -i "s/# as directory, then fall back to displaying a 404./rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
