#!/usr/bin/env bash
# Setup Nginx redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo rm /var/www/html/index.nginx-debian.html
echo 'Hello World' >> /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
