#!/usr/bin/env bash
# This is a comment

sudo apt-get update
sudo apt -y install haproxy
echo "frontend Local_Server
    bind *:80
    mode http
    default_backend My_Web_Servers

backend My_Web_Servers
    balance roundrobin
    server web1 34.148.177.223:80 check
    server web2 34.139.245.214:80 check" >> /etc/haproxy/haproxy.cfg;
systemctl restart haproxy;
