#!/usr/bin/env bash
# This is a useless comment
echo $$ > /var/run/myscript.pid
trap 'rm /var/run/myscript.pid | kill "$$"' SIGQUIT
trap 'echo I hate the kill command | rm /var/run/myscript.pid | kill "$$"' SIGTERM
trap "echo Y U no love me?! " SIGINT
time=2
while ((time % 2 == 0))
do
	echo "To infinity and beyond"
	sleep $time
done
