#!/usr/bin/env bash
# This is a useless comment
echo $$ > /var/run/myscript.pid
trap 'sudo rm /var/run/myscript.pid' 3 15
trap 'kill "$$"' 3
trap "echo I hate the kill command" 15
trap "echo Y U no love me?! " 2
time=2
while ((time % 2 == 0))
do
	echo "To infinity and beyond"
	sleep $time
done
