#!/usr/bin/env bash
# This script display BestSchool 10 times
file=/etc/passwd
i=$(wc -l /etc/passwd | cut -d' ' -f1)
c=1
while ((c != i))
do
	username=$(awk NR==$c $file | cut -d':' -f1)
	groupe=$(awk NR==$c $file | cut -d':' -f3)
	homedir=$(awk NR==$c $file | cut -d':' -f6)
	command=$(awk NR==$c $file | cut -d':' -f7)
	uid=$(awk NR==$c $file | cut -d':' -f4)
	password=$(awk NR==$c $file | cut -d':' -f2)
	echo "The user $username is part of the $groupe gang, lives in $homedir and rides $command. $uid's place is protected by the passcode $password, more info about the user here: $username"
	c=$((c+1))
done