#!/usr/bin/env bash
# This script display BestSchool 10 times
i=1
while (( i != 21 ))
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
	;;
	9)
		echo "bad luck from Japan"
	;;
	18)
		echo "bad luck from Italy"
	;;
	esac
	i=$((i+1))
done
