#!/usr/bin/env bash
# This script display BestSchool 10 times
hours=0
minutes=0
while (( hours <= 12 ))
do
	echo "Hour: $hours"
	while ((minutes <= 59))
	do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
	minutes=0
done
